version: '3'
services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper:/data
      - ./logs/zookeeper:/logs

  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
      - ./logs/kafka1:/var/lib/kafka/logs

  kafka2:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
      - kafka1
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    volumes:
      - ./data/kafka2:/var/lib/kafka/data
      - ./logs/kafka2:/var/lib/kafka/logs
